# Generated by Django 5.2.4 on 2025-07-19 10:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                ("surname", models.CharField(blank=True, max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Fe", "Female"), ("M", "Male")],
                        default="1",
                        max_length=2,
                    ),
                ),
                ("email", models.EmailField(max_length=250)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=70)),
                ("country", models.CharField(blank=True, max_length=70)),
                ("continent", models.CharField(blank=True, max_length=70)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, upload_to="uploads/pro_picture/"),
                ),
                ("about", models.TextField(blank=True, max_length=400)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 7, 19, 13, 34, 38, 315586)
                    ),
                ),
                ("like", models.IntegerField(default=0)),
                ("post_title", models.CharField(max_length=50)),
                ("post_text", models.TextField(max_length=10000)),
                (
                    "post_image",
                    models.ImageField(blank=True, upload_to="uploads/post_image/"),
                ),
                ("comment_count", models.IntegerField(default=0)),
                (
                    "tag_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="page.tag"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="page.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(max_length=200)),
                (
                    "user_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="page.userpost"
                    ),
                ),
                (
                    "commenter_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="page.userprofile",
                    ),
                ),
            ],
        ),
    ]
