# Generated by Django 5.2.4 on 2025-07-19 11:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_alter_userpost_date_time_alter_userpost_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpost",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 19, 14, 21, 46, 449150)
            ),
        ),
        migrations.AlterField(
            model_name="userpost",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
