# Generated by Django 5.2 on 2025-07-21 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_alter_userpost_date_time_alter_userpost_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpost",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 21, 23, 55, 42, 504777)
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[(None, ""), ("Fe", "Female"), ("M", "Male")],
                default=1,
                max_length=2,
            ),
        ),
    ]
