# Generated by Django 5.2 on 2025-07-22 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0004_alter_userpost_date_time_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpost",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 22, 19, 31, 49, 502854)
            ),
        ),
        migrations.RemoveField(
            model_name="userpost",
            name="tag_category",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    (None, "Select Gender"),
                    ("Female", "Female"),
                    ("Male", "Male"),
                ],
                default=1,
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="userpost",
            name="tag_category",
            field=models.ManyToManyField(blank=True, to="page.tag"),
        ),
    ]
