# Generated by Django 5.2.4 on 2025-08-16 14:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0007_alter_userpost_date_time_alter_userpost_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpost",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 16, 17, 7, 32, 540432)
            ),
        ),
        migrations.CreateModel(
            name="ChildComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_comment", models.TextField(max_length=200)),
                (
                    "commenter_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="page.userprofile",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="page.comment"
                    ),
                ),
                (
                    "user_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="page.userpost"
                    ),
                ),
            ],
        ),
    ]
